class CreateVendor10s < ActiveRecord::Migration[5.0]
  def change
    create_table :vendor10s do |t|
      t.text :col_0
      t.text :col_1
      t.text :col_2
      t.text :col_3
      t.text :col_4
      t.text :col_5
      t.text :col_6
      t.text :col_7
      t.text :col_8
      t.text :col_9
      t.text :col_10
      t.text :col_11
      t.text :col_12
      t.text :col_13
      t.text :col_14
      t.text :col_15
      t.text :col_16
      t.text :col_17
      t.text :col_18
      t.text :col_19
      t.text :col_20
      t.text :col_21
      t.text :col_22
      t.text :col_23
      t.text :col_24
      t.text :col_25
      t.text :col_26
      t.text :col_27
      t.text :col_28
      t.text :col_29
      t.text :col_30
      t.text :col_31
      t.text :col_32
      t.text :col_33
      t.text :col_34
      t.text :col_35
      t.text :col_36
      t.text :col_37
      t.text :col_38
      t.text :col_39
      t.text :col_40
      t.text :col_41
      t.text :col_42
      t.text :col_43
      t.text :col_44
      t.text :col_45
      t.text :col_46
      t.text :col_47
      t.text :col_48
      t.text :col_49
      t.text :col_50
      t.text :col_51
      t.text :col_52
      t.text :col_53
      t.text :col_54
      t.text :col_55
      t.text :col_56
      t.text :col_57
      t.text :col_58
      t.text :col_59
      t.text :col_60
      t.text :col_61
      t.text :col_62
      t.text :col_63
      t.text :col_64
      t.text :col_65
      t.text :col_66
      t.text :col_67
      t.text :col_68
      t.text :col_69
      t.text :col_70
      t.text :col_71
      t.text :col_72
      t.text :col_73
      t.text :col_74
      t.text :col_75
      t.text :col_76
      t.text :col_77
      t.text :col_78
      t.text :col_79
      t.text :col_80
      t.text :col_81
      t.text :col_82
      t.text :col_83
      t.text :col_84
      t.text :col_85
      t.text :col_86
      t.text :col_87
      t.text :col_88
      t.text :col_89
      t.text :col_90
      t.text :col_91
      t.text :col_92
      t.text :col_93
      t.text :col_94
      t.text :col_95
      t.text :col_96
      t.text :col_97
      t.text :col_98
      t.text :col_99
      t.text :col_100

      t.timestamps
    end
  end
end
